### ISSUE TITLE
Possible incidental capitilisation of false to False in xml->yaml->json conversion

### ISSUE THREAD

**Issue by damiankennedy2012** [Avanade/Beef#105]
Hi,
Have regenerated our entity code and the following capitalisation of 'false' has appeared in a few places:
```
        public override bool IsInitial
        {
            get
            {
                return False;
            }
        }
```
This occurs whenever the entity attribute `IsInitialOverride="false"` is used.

**Comment by chullybun** [comment]
Hi @damiankennedy2012, this has been corrected. NuGet package `Beef.CodeGen.Core` version `4.1.17` has been published. Cheers...

**Comment by damiankennedy2012** [comment]
Cheers, all good now.
