### ISSUE TITLE
Add global:: to SuppressMessage attribute in generated Data classes

### ISSUE THREAD

**Issue by Simke11** [Avanade/Beef#111]
We've got a domain named XYZ.System.
Data classes have SuppressMessage attribute is fully qualified, System.Diagnostics.CodeAnalysis.SuppressMessage.
This causes compiler error "The type or namespace name 'Diagnostics' does not exist in the namespace 'XYZ.System'".
Changing it global::System.Diagnostics.CodeAnalysis.SuppressMessage would resolve this issue.

**Comment by chullybun** [comment]
Hey @Simke11, are you using the latest nuget packages. I removed those `SuppressMessage` instances not so long ago. Cheers...

**Comment by Simke11** [comment]
Upgrading to the very latest Beef is still on our to do list...:) Good to know its resolved, I do have a workaround for it for now
