### ISSUE TITLE
Annotation1 tag no longer supports '[' or ']' characters in code gen

### ISSUE THREAD

**Issue by Nathan-Priebe** [Avanade/Beef#124]
I have hit an issue after upgrading Beef.Codegen.Core from v4.1.14 to v4.1.18. In some of our entities we use the Annotation1 tag with the value wrapped in square braces. Following the upgrade to v.4.1.18 the codegen fails as the contents of the xml file are not valid. If I remove the square braces the code gen runs through but the generated entities are left with annotations not wrapped in square braces which caused the build to fail. 

Console output from running the project

```
Business Entity Execution Framework (Beef) Code Generator.

  Config = Bps.PrOS.TenantGateway.xml
  Script = EntityWebApiCoreAgent.xml
  Template = 
  Output = C:\Users\nathan.priebe\source\repos\Bps.PrOS.TenantGateway
  ExpectNoChange = False
  Params:
    Company = Bps.PrOS
    AppName = TenantGateway
    ApiName = Api

dotnet : The contents of the Config File Bps.PrOS.TenantGateway.xml are not valid.
At line:1 char:1
+ dotnet run all
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The contents of... are not valid.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError`
 
Unexpected character encountered while parsing value: [. Path 'entities[52].properties[0].annotation1', line 1, position 36983.
```
Example codegen XML
```
<Entity Name="User" Text="User" ExcludeAll="true" ExcludeData="false" AutoImplement="Database" OmitEntityBase="true">
   <Property Name="Id" Type="int" Annotation1="[XmlElement(&quot;Id&quot;)]"/>
</Entity>
```

Beef.Codegen.Core Version: v4.1.18

**Comment by chullybun** [comment]
@Nathan-Priebe - hey bro, this should now be fixed. You'll need to get the latest packages.
