### ISSUE TITLE
'not' is giving error

### ISSUE THREAD

**Issue by basharathussain** [Avanade/Beef#130]
Hi, I am getting a compilation error, you help is required. I am using VS2019. 
Error: The type or namespace name 'not' could not be found (are you missing a using directive or an assembly reference?)	
Line: if (from is not T val)

Code:
 protected static T ValidateCopyFromType<T>(object from) where T : class
        {
            Check.NotNull(from, nameof(from));

            if (from is not T val)
                throw new ArgumentException($"Cannot copy from Type '{from?.GetType().FullName}' as it is incompatible.", nameof(from));

            return val;
        }

**Comment by chullybun** [comment]
I dislike saying "it works on my machine" - however, it is successfully compiling at my end. What version of Visual Studio 2019 are you using (I am currently on v16.9.4)?

**Comment by chullybun** [comment]
@basharathussain - have you had an opportunity to try again. I have confirmed it compiles on a second machine. At this stage I will look to close this issue, unless further information can be provided to duplicate. Cheers...

**Comment by basharathussain** [comment]
Yes thank you very much. after updating the VS2019 version to the latest (16.10.4), it worked fine.
