### ISSUE TITLE
Unable to exclude all layers except manager, and have a custom manager

### ISSUE THREAD

**Issue by Nathan-Priebe** [Avanade/Beef#141]
If I use the below codegen, I'd except a generated manager to be created with an operation pointing to my custom manager. With no reference to any Data or DataSvc classes.

```
<Entity Name="Example" Text="Example" WebApiRoutePrefix="api/v1/Example" AutoImplement="None" ExcludeData="true" ExcludeIData="true" ExcludeIDataSvc="true" ExcludeDataSvc="true">
    <Operation Name="Example" OperationType="Get" ReturnType="Example" AutoImplement="None" WebApiAuthorize="Authorize" ManagerCustom="true"/>
</Entity>
```

The result of the above codegen is that I do get a correctly generated manager. However, the generated manager is still trying to reference `*.DataSvc` in the using statements.

The work around I have for this at the moment is to generate the data and datasvc for the entity while excluding it for any operations. This works but generates extra classes that may never be used. 

```
<Entity Name="Example" Text="Example" WebApiRoutePrefix="api/v1/Example" AutoImplement="None" >
    <Operation Name="Example" OperationType="Get" ReturnType="Example" AutoImplement="None" WebApiAuthorize="Authorize" ExcludeData="true" ExcludeIData="true" ExcludeIDataSvc="true" ExcludeDataSvc="true" ManagerCustom="true"/>
</Entity>
```

Another work around is to exclude manager as well and write everything except for the controller by hand. But this removes the benefit of having the codegen hook up the service collection.

**Comment by chullybun** [comment]
Hi @Nathan-Priebe,

I pasted your XML into my test, and a brand new project, and it output correctly both times:

``` csharp
    public partial class ExampleManager : IExampleManager
    {
        ...
        public async Task<Example?> ExampleAsync()
        {
            return await ManagerInvoker.Current.InvokeAsync(this, async () =>
            {
                return Cleaner.Clean(await ExampleOnImplementationAsync().ConfigureAwait(false));
            }, BusinessInvokerArgs.Read).ConfigureAwait(false);
        }
```

I am unable to recreate your issue? 

Cheers...

**Comment by chullybun** [comment]
@Nathan-Priebe, this is now fixed in NuGet `Beef.CodeGen.Core` package version `4.2.2`.
