### ISSUE TITLE
Sql Text/NText columns cant be used in the Cdc Code Generator as they arent mapped to a .NET type

### ISSUE THREAD

**Issue by ciaranodonnell** [Avanade/Beef#161]
Pointing the Code Generator at a column of type TEXT gives this error

`Unhandled exception. System.InvalidOperationException: Database data type 'text' does not have corresponding .NET type mapping defined.`

**Comment by chullybun** [comment]
Fix in NuGet Package `Beef.CodeGen.Core` version `4.2.11` just published.
