### ISSUE TITLE
Feature idea - redirect from / to swagger

### ISSUE THREAD

**Issue by karpikpl** [Avanade/Beef#168]
Microsoft samples have redirect from `/` to `/swagger`
That could be part of code generation
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Catalog/Catalog.API/Controllers/HomeController.cs

**Comment by chullybun** [comment]
This support is enabled using Swagger configuration; the _Beef_ template outputs this by default in the API [`Startup`](https://github.com/Avanade/Beef/blob/master/templates/Beef.Template.Solution/content/Company.AppName.Api/Startup.cs):

``` csharp
        app.UseSwaggerUI(c =>
        {
            c.RoutePrefix = ""; // Default as the root/home page.
            c.SwaggerEndpoint("/swagger/v1/swagger.json", "Company.AppName");
        });
```
