### ISSUE TITLE
Bug in fnGetUsername

### ISSUE THREAD

**Issue by vishal-sharma** [Avanade/Beef#17]
There is a bug in https://github.com/Avanade/Beef/blob/master/tools/Beef.Database.Core/Schema/dbo/Functions/fnGetUsername.sql

It uses convert function incorrectly to read username from session context.

SET @Username = CONVERT(nvarchar, SESSION_CONTEXT(N'Username'));

Username is defined a varchar of length 50 in function: 
DECLARE @Username nvarchar(50)

But above usage of Convert shall only use 30 characters by default. It needs to be changed to:
SET @Username = CONVERT(nvarchar(50), SESSION_CONTEXT(N'Username'));

It is documented in Microsoft docs [here](https://docs.microsoft.com/en-us/sql/t-sql/data-types/char-and-varchar-transact-sql?view=sql-server-ver15#b-showing-the-default-value-of-n-when-varchar-is-used-with-cast-and-convert)

**Comment by chullybun** [comment]
This has been resolved.
