### ISSUE TITLE
.ExpectChangeLogCreated( ) fails when API takes a little longer to return value.

### ISSUE THREAD

**Issue by leandrodotec** [Avanade/Beef#188]
.ExpectChangeLogCreated( ) fails when API takes a little longer to return value.
This is the message:
" Expected IChangeLog.CreatedDate actual '09/27/2022 21:44:19' to be greater than expected '09/27/2022 21:44:20'. "

This is the code that sometimes fails when we run it in our CI/CD pipeline.
```
           var created = AgentTester.Test<ClaimInvoiceAgent, ClaimInvoice>()
                .ExpectChangeLogCreated( )
                .ExpectStatusCode(HttpStatusCode.OK)
                .Run(a => a.UpsertAsync(input))
                .Value;
```

Looking at AgentTestV.cs, I see that the function assumes some defaults,  

```
public AgentTest<TStartup, TAgent, TValue> ExpectChangeLogCreated(string? createdby = null, DateTime? createdDateGreaterThan = null)
        {
            Check.IsTrue(typeof(TValue).GetInterface(typeof(IChangeLog).Name) != null, "TValue must implement the interface IChangeLog.");

            _isExpectCreatedBy = true;
            _changeLogCreatedBy = string.IsNullOrEmpty(createdby) ? Username : createdby;
            _changeLogCreatedDate = createdDateGreaterThan ?? (DateTime?)Cleaner.Clean(DateTime.Now.Subtract(new TimeSpan(0, 0, 1)));
            _comparisonConfig.MembersToIgnore.AddRange(new string[] { "ChangeLog" });
            return this;
        }
```

Question:  when does ExpectChangeLogCreated( ) get called? 
Looking at the way we use it in  the code,  ExpectChangeLogCreated( ) seems to be called before the API, but the assertion is failing by 1 second, so I am not sure.

**Comment by chullybun** [comment]
hi @leandrodotec. `ExpectChangeLogCreated` sets an expectation when you call it, basically saying that the `CreatedDate` should be greater than current time less 1 second (to allow for minor discrepancy in time) which is then validated after it executes - see [here](https://github.com/Avanade/Beef/blob/dc85236678bcd3512507ab0802e873041130a758/tools/Beef.Test.NUnit/Tests/AgentTestV.cs#L354). I am unable to reproduce your behaviour?

**Comment by leandrodotec** [comment]
Yeah, it is hard to reproduce. I will see if I can do it by forcing delays in the middle of a Data layer.

**Comment by leandrodotec** [comment]
Can't reproduce in a way that I can report the bug, it is only happening in Azure pipeline runs. I will close this one.
