### ISSUE TITLE
OmitEntityBase breaks entities when used with a custom PathCommon

### ISSUE THREAD

**Issue by Nathan-Priebe** [Avanade/Beef#193]
Beef codegen version: 4.2.1.8

When generating entities with OmitEntityBase and a custom PathCommon, the entity generated is no longer a simple POCO object. Instead, it appears as though it attempts to generate a full entity.

How to replicate:
1. Setup normal Beef project
2. Set entity with OmitEntityBase="true"
4. Set a PathCommon to a new project that isn't *.Common
5. Generated entities are full entities in the PathCommon project despite the OmitEntityBase setting

**Comment by chullybun** [comment]
Howdy @Nathan-Priebe, apologies it took a little longer than expected to get to this issue. Published new `Beef.CodeGen.Core` package, version `4.2.19`, that should resolve. Let me know how you get on. Cheers.
