### ISSUE TITLE
Ref data code gen for ref data with additional properties puts ConfigureAwait(false) where it shouldn't

### ISSUE THREAD

**Issue by Simke11** [Avanade/Beef#23]
When genning ref data with additional properties, e.g.
```xml
<Entity Name="MyRefDataEntity" RefDataType="Guid" Collection="true" WebApiRoutePrefix="api/v1/ref/myRefDataEntity" AutoImplement="Database" DatabaseSchema="Ref" ConstType="string" >
    <Property Name="MyProperty" Type="bool" />
</Entity>
```

Gen'd method for the entity's GetAllAsync produces the following code for getting the property value
```csharp
item.MyProperty= dr.GetValue<bool>("MyProperty").ConfigureAwait(false);
```

After code gen is ran, compile fails due to ConfigureAwait(false).

ConfigureAwait(false) is added there via line 154 in ReferenceDataData_cs.xml.

**Comment by chullybun** [comment]
Resolved.
