### ISSUE TITLE
Changing the default entity to something other than person results in an invalid solution being generated

### ISSUE THREAD

**Issue by ravensorb** [Avanade/Beef#26]
It looks like if I change the Entities xml file to create an entity of something other than person, the args, code, validators code and test project still are generated with the default person model.

Note: I changed the entity, the operation, and the args, and the ref data.

Am I missing something?

**Comment by chullybun** [comment]
The code you are referencing is added during the process of creating the solution using `dotnet new`, not as part of the code generation. Files generated are always placed in a directory named "Generated". You will need to remove any files named `Person*` from the solution after creation; this is described in https://github.com/Avanade/Beef/tree/master/samples/Cdr.Banking. I will look to add an option in the `dotnet new` function to only add on request. Thanks for the feedback.

**Comment by chullybun** [comment]
On further reflection I have decided to close this issue. There is value in having the `Person*` artefacts created as helpers, and they are simple enough to remove where not needed.
