### ISSUE TITLE
Can't access MinCount and MaxCount validators for a collection

### ISSUE THREAD

**Issue by nissan** [Avanade/Beef#29]
Hi, 
I'm trying to use a Beef Validation element for checking minimum and maximum counts in Collections. See https://github.com/Avanade/Beef/blob/master/docs/Beef-Validation.md but i don't seem to have access to the properties it mentions here. (see under Rules--> CollectionRule --> MinCount, MaxCount)
I would expect the syntax to chain like this ` Property(x => x.Items).Collection(item: new CollectionRuleItem<MyItemField>(MyItemFieldValidator.Default)).MaxCount(100);` but the MaxCount property isn't being recognised. Am I using the syntax correctly? Are there any sample code available where one is trying to restrict the size of a collection to at least some MinCount value and no more than MaxCount items in the collection ?

**Comment by chullybun** [comment]
Hi there. 

The Min and MaxCount are set using the `Collection` method itself. So your code should look like:

`Property(x => x.Items).Collection(item: <collectionruleitem>, minCount: 1, maxCount: 10);`.

Hope this helps. Let me know if you have any further issues.

**Comment by nissan** [comment]
Thanks, this worked!
