### ISSUE TITLE
Null Reference Exception in generated Data Service class

### ISSUE THREAD

**Issue by edjo23** [Avanade/Beef#34]
Hi, the last update has introduced an issue in the generated Data Service class. The following generated code throws a null reference exception when the result from the data operation is null.

```
        public static Task<Tenant> GetByHostNameAsync(string? hostName)
        {
            return DataSvcInvoker.Default.InvokeAsync(typeof(TenantDataSvc), async () => 
            {
                var __result = await Factory.Create<ITenantData>().GetByHostNameAsync(hostName).ConfigureAwait(false);
                ExecutionContext.Current.CacheSet(__result.UniqueKey, __result);
                if (_getByHostNameOnAfterAsync != null) await _getByHostNameOnAfterAsync(__result, hostName).ConfigureAwait(false);
                return __result;
            });
        }
```

This is generated using:
```
  <Entity Name="Tenant" Text="Tenant configuration" Implements="IETag, IChangeLog, ITenant" Collection="true" WebApiRoutePrefix="api/v1/tenants" CollectionResult="true" 
          AutoImplement="Database" DatabaseSchema="dbo">
    ...
    <Operation Name="GetByHostName" OperationType="Custom" ReturnType="Tenant" WebApiRoute="hostName/{hostName}" WebApiMethod="HttpGet">
      <Parameter Name="HostName" Type="string" />
    </Operation>
  </Entity>
```

I think this is due to the change to line 481 - https://github.com/Avanade/Beef/blame/master/tools/Beef.CodeGen.Core/Templates/EntityDataSvc_cs.xml#L481

```
ExecutionContext.Current.CacheSet<{{Operation.ReturnType}}>(__result?.UniqueKey ?? UniqueKey.Empty, __result);
```
has been changed to:
```
ExecutionContext.Current.CacheSet(__result.UniqueKey, __result);
```

**Comment by chullybun** [comment]
Hi. This is a combination of things primarily related to the Nullable Reference Type support that was recently added. The issue is because the `Type` was not defined as nullable, therefore it is assumed it should not be null - and because it was null, the `NullReferenceException` was thrown.

I have made a fix within the code generation to support a nullable `ReturnType` where using  `OperationType="Custom"` if a null result is considered valid; e.g. `ReturnType="Tenant?"`

You will need to amend your XML to add the nullable `?` to the `ReturnType` and re-run the code generation using the latest NuGet packages (just published).

**Comment by edjo23** [comment]
Thanks @chullybun, can confirm that when we add a `?` to the return type it is now working as expected. We did find though if we didn't add the `?` the cache line is not include in the gen code at all. I made a comment on the commit as to why I think that is happening.

**Comment by edjo23** [comment]
Link to comment - https://github.com/Avanade/Beef/commit/9d0e4362b05a96dbb49ddb90391030d069b8d2a0#r39025982 ... but basically there is a `'` character which I think is causing the issue.

**Comment by edjo23** [comment]
I've created PR https://github.com/Avanade/Beef/pull/38 for the fix.

**Comment by chullybun** [comment]
Thanks @edjo23 - I have merged in the PR and published an updated NuGet package for `Beef.CodeGen.Core` v3.1.7.

**Comment by edjo23** [comment]
Thanks
