### ISSUE TITLE
Validation of a Collection for duplicate items

### ISSUE THREAD

**Issue by nissan** [Avanade/Beef#36]
I am trying to validate that a collection of objects does not contain duplicates, i.e., if collection A has objects with properties x,y,z, that for any members in the collection e.g. a,b,c, that no duplicates exist, i.e. a.x==b.x && a.y==b.y && a.z==b.z or the same for any other element comparison. Is there a simple way to do this within the validator? I currently have a validator property like `Property(x => x.Items).Collection(
                item: new CollectionRuleItem<MyElementCollection>(MyElementCollectionValidator.Default),
                minCount: 0,
                maxCount: 100);` but can't seem to find a "noDuplicates" or similar. Any assistance here would be much appreciated.

**Comment by chullybun** [comment]
Hi there. The easiest way to achieve this is by using the `UniqueKey` capability that can be added to an entity. Typically, this is used for the `Id` property on an entity, declared within the `entity.xml`. Therefore, add `UniqueKey="true"` to your properties `X`, `Y` and `Z` to code-gen the entity support. 

The update your validation logic to check for duplicates the `UniqueKeyDuplicateCheck` method needs to be invoked: `Property(x => x.Items).Collection( item: new CollectionRuleItem<MyElementCollection>(MyElementCollectionValidator.Default).UniqueKeyDuplicateCheck(), minCount: 0, maxCount: 100);`

Hope this helps.

**Comment by nissan** [comment]
This worked much simpler than the Custom validation logic I had written before! Thank you so much!
