### ISSUE TITLE
Converting Nullable Enum in DataRecord GetValue

### ISSUE THREAD

**Issue by damiankennedy2012** [Avanade/Beef#39]
https://github.com/Avanade/Beef/blob/master/src/Beef.Data.Database/DatabaseRecord.cs

A call to GetValue such as:

myDataRecord.GetValue<MyEnum?>("MyFieldName");

Gives the error:

System.InvalidCastException : Invalid cast from 'System.Byte' to 'MyEnum'.

It seems that typeof(T).IsEnum returns false if T is a Nullable Enum. However, in GetValue the variable nt is set to the underlying type and nt.IsEnum returns true

**Comment by damiankennedy2012** [comment]
I have added a pull-request with the suggested change.

**Comment by chullybun** [comment]
Hi @damiankennedy2012 - PR was accepted and NuGet packages published. Thanks for contributing :-)
