### ISSUE TITLE
DataContextScope.GetContext duplicate key error

### ISSUE THREAD

**Issue by damiankennedy2012** [Avanade/Beef#42]
I have also created a pull request for this one, when being called in parallel, for example when a generated ReferenceDataProvider executes:

Parallel.ForEach(types, (type, state) => { var x = this[type]; });

a second thread can get past the initial key check in GetContext while the first thread is still waiting for a connection to open resulting in an attempt to add the key twice.

The pull request just contains a lock around this code.

**Comment by chullybun** [comment]
Hi @damiankennedy2012 - PR was accepted and NuGet packages published. Thanks for contributing :-)
