### ISSUE TITLE
CreateJsonResultAndETag( ) should return a consistent result.

### ISSUE THREAD

**Issue by leandrodotec** [Avanade/Beef#60]
**What is wrong?**

When an entity _does not implement IEtag_, given 2 different calls that produce the same collection, CreateJsonResultAndETag( ) function from Beef.AspNetCore.WebApi.WebApiActionBase class returns different ETag values when API is called with ExcludeFields and returns the same ETag when API is called without ExcludeFields.

**What is expected?**

EDIT:  
Expected to return the same ETag for the collection when entity does not implement IETag and returns a calculated ETag when entity implements IETag.

or

 WebApiGet<TResult, TColl, TEntity> should not call CreateJsonResultAndETag( ) and  should not set ETag header when items from a Collection do not implement IETag.

**How to reproduce:**

codegen xml:
```
<Entity Name="Contact" Collection="true" CollectionResult="true" WebApiRoutePrefix="api/v1/contacts" 
          AutoImplement="Database" Implements="Changelog">
    <Property Name="Id" Type="Guid" UniqueKey="true"/>
    <Property Name="Name" Type="string" DataName="ContactTypeCode" />
 <Operation Name="GetByArgs" OperationType="GetColl" PagingArgs="true">
      <Parameter Name="search" Type="string"/>
    </Operation>
</Entity>
```

_**unit test:**_

Assume the database has 2 contacts: "Mary Flower" and "Mary Smith".

```
[Test]
        public void A152_GetByArgs_CheckETagWithoutAddingPatient_WithExcludeFields()  
        {

            var contactArgs = "Mary" ;
            var pagingArgs = new Beef.Entities.PagingArgs { IsGetCount = true };
            var webReqOptions = new Beef.WebApi.WebApiRequestOptions().Exclude("changeLog");

            var originalEtag = AgentTester.Create<ContactAgent, ContactCollectionResult>()
                .ExpectStatusCode(HttpStatusCode.OK)
                .Run((a) => a.Agent.GetByArgsAsync(contactArgs, pagingArgs, webReqOptions)).Response.Headers.ETag;

 /****

Update contact name to "Mary Anne"

(details hidden for brevity)
******/


            var newEtag = AgentTester.Create<ContactAgent, ContactCollectionResult>()
                .ExpectStatusCode(HttpStatusCode.OK)
                .Run((a) => a.Agent.GetByArgsAsync(contactArgs, pagingArgs, webReqOptions)).Response.Headers.ETag;

//This test passes
            Assert.AreNotEqual(originalEtag, newEtag, "ETag should not be the same after an update.");
        }

        [Test]
        public void A153_GetByArgs_CheckETagWithoutAddingPatient_WithAllFields()
        {
            var contactArgs = "Mary" ;
            var pagingArgs = new Beef.Entities.PagingArgs { IsGetCount = true };
 
            var originalEtag = AgentTester.Create<ContactAgent, ContactCollectionResult>()
                .ExpectStatusCode(HttpStatusCode.OK)
                .Run((a) => a.Agent.GetByArgsAsync(contactArgs, pagingArgs)).Response.Headers.ETag;
 /****

Update contact name to "Mary Anne"

(details hidden for brevity)
******/
            var newEtag = AgentTester.Create<ContactAgent, ContactCollectionResult>()
                .ExpectStatusCode(HttpStatusCode.OK)
                .Run((a) => a.Agent.GetByArgsAsync(contactArgs, pagingArgs)).Response.Headers.ETag;

//This test fails
            Assert.AreNotEqual(originalEtag, newEtag, "ETag should not be the same after an update.");
        }
```

**Comment by leandrodotec** [comment]
Hi again. just adding to the details:

I managed to find out why:

JsonPropertyFilter.ApplyAsObject  returns a JToken of the value when it is called with a ExcludeField or IncludeField.

But

JsonPropertyFilter.ApplyAsObject  returns the value itself when there is no ExcludeField and IncludeField.

That leads to the unconsistent behaviour. This line from CreateJsonResultAndETag():

`var buf = Encoding.UTF8.GetBytes($"{(sb != null && sb.Length > 0 ? sb.ToString() : json)}{AsciiDivider}{context?.HttpContext.Request.QueryString.Value}");
`

When _json_  is just a ContactCollection, will set _buf_ with "ContactCollection|?search=mary&%24take=25&%24count=true"  regardless of its values.  This generates the same EToken every time.

But when _json_ variable has a JToken the line will set _buf_ to something like below, which generates different EToken when the collection items are different.
```
[
  {
    "id": "00000002-0000-0000-0000-000000000000",
    "name": "myname",
  },
  {
    "id": "0000000a-0000-0000-0000-000000000000",
    "name": "other name",
  }
]|?search=mary&%24take=2&%24count=true&$exclude=changeLog
```

**Comment by edjo23** [comment]
Hi @leandrodotec, Dan here. Yeah I see the issue, as you said `JsonPropertyFilter.ApplyAsObject` just returns an object when there is no include or exclude properties. The string interpolation used to generate the hash will just resolve to the type name, e.g. "SomeNamespace.ContactCollection" everytime, regardless of it's contents. Which in turn will always return the same ETag.

@chullybun, maybe the JsonPropertyFilter.ApplyAsObject method should always return JSON. E.g. this line here: https://github.com/Avanade/Beef/blob/c130bb7a981e483dede9f42316c5a78c8b4a3b4f/src/Beef.Core/Json/JsonPropertyFilter.cs#L33 
Becomes `return JToken.FromObject(value);`.

Or is there a more efficient way? Maybe using GetHashCode?

**Comment by chullybun** [comment]
@leandrodotec and @edjo23, thanks. I have fixed the issue, and have gone down the `GetHashCode` route. A new version of the `Beef.AspNetCore.WebApi` nuget package has been published. As an FYI, I am wanting to avoid doing any JSON serialization unless absolutely necessary and let ASP.NET Core framework handle. Eventually, I will make using the native or Newtonsoft serializer configurable, versus just Newtonsoft as it is now and this helps enable.

**Comment by karpikpl** [comment]
Just FYI - Microsoft is moving away from Newtonsoft  https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to

although their implementation is missing a lot of features Newtosoft has :/

**Comment by chullybun** [comment]
Hi @karpikpl. Exactly, it is missing key features. As such, I am deferring adoption until those features exist - probably in the .NET 5 timeframe. Recognizing the need to migrate was the consideration for the above approach to minimize dependencies and allow ASP.NET native to enable.

**Comment by chullybun** [comment]
@leandrodotec and @edjo23, did this resolve the issue at your end? Just wanting to close out the issue. Cheers.

**Comment by leandrodotec** [comment]
Hi @chullybun, using GetHashCode makes sense.
