### ISSUE TITLE
Code generated won't compile for get operations that have no parameters

### ISSUE THREAD

**Issue by edjo23** [Avanade/Beef#63]
Bit of an unusual scenario but we have a get endpoint that does not have parameters.

This entity xml:
```xml
  <Entity Name="Staging" WebApiRoutePrefix="api/v1/staging">
    <Property Name="Id" Type="string" />
    <Property Name="Uri" Type="string" />
    <Property Name="Token" Type="string" />

    <Operation Name="Get" OperationType="Get" AutoImplement="None" />
  </Entity>
```

Generates fine except for the partial function hooks, they generate with a missing comma.

In StagingManager:
```cs
private readonly Func<Staging?Task>? _getOnAfterAsync;
```

In StagingDataSvc:
```cs
private static readonly Func<Staging?Task>? _getOnAfterAsync;
```

The generated code has to be modified before it can compile.

**Comment by chullybun** [comment]
Hi @edjo23. This has been fixed and the corresponding nuget package [`Beef.CodeGen.Core v3.1.18`](https://www.nuget.org/packages/Beef.CodeGen.Core/3.1.18) published.

**Comment by edjo23** [comment]
Confirming that fix has worked.
