### ISSUE TITLE
Beef DB generation fails on Linux/OSX

### ISSUE THREAD

**Issue by karpikpl** [Avanade/Beef#66]
**Steps to reproduce**
1. clone the repo
2. execute:
```
 ~/projects/Beef/samples/Demo/Beef.Demo.Database     master  
   dotnet run all
```

**Expected:**
DB updated with schema and ref data

**Actual:**
Error:
`The directory '.\..' does not exist.`

**Analysis:**
Path reference does not work on OSX:
**/Beef/tools/Beef.CodeGen.Core/CodeGenConsoleWrapper.cs**
```
string outDir = ".\\.."
```

Replacing outDir with `./..` solves the issue on OSX.

@chullybun - is there a way to override that param?
passing `-o` causes this error `"Unrecognized option '-o'"`

**Comment by karpikpl** [comment]
I haven't found a good solution for this yet.

The default value has to be replaced with `static readonly` since https://docs.microsoft.com/en-us/dotnet/api/system.io.path.directoryseparatorchar?view=netcore-3.1 is static readonly

**Comment by karpikpl** [comment]
hey @chullybun 
I've reproduced this issue on official Microsoft dotnet core image

```bash
root@6be8d9bff878:/#  docker run -ti --mount source="$(pwd)",target=/app,type=bind -t mcr.microsoft.com/dotnet/core/sdk:3.1 /bin/bash
root@6be8d9bff878:/# cd app/Sempra.TM2.Database/
root@6be8d9bff878:/app/Sempra.TM2.Database# dotnet run Database -cs "Server=localhost; Database=TM3; User id=sa; Password=xxxxxx"
The directory '.\..' does not exist.
Specify --help for a list of available options and commands.
```

**Comment by chullybun** [comment]
Hey @karpikpl, fix applied and packages pushed to NuGet. Let me know how you get on. Cheers :-)

**Comment by karpikpl** [comment]
Hey @chullybun 
I was able to run database generation on Beef Master on OSX without any issues!


I see some strange behaviors with sample project though - not sure if related.

Steps to reproduce:
1. clone Beef master branch
2. go to samples/demo
3. execute `dotnet test Beef.Demo.Test`

Expected
Test Pass

Actual:
```
SetUp failed for test fixture Beef.Demo.Test.XParallelPersonTest
Multiple failures or warnings in test:
  1) This RegisterSetUp function failed to execute successfully.
  2) This RegisterSetUp function failed to execute successfully: This RegisterSetUp function failed to execute successfully.

   at Beef.Test.NUnit.TestSetUp.InvokeRegisteredSetUp() in /Users/piotr.karpala/projects/Beef/tools/Beef.Test.NUnit/TestSetUp.cs:line 143
   at Beef.Test.NUnit.AgentTester..ctor(String username, Object args) in /Users/piotr.karpala/projects/Beef/tools/Beef.Test.NUnit/AgentTester.cs:line 459
   at Beef.Test.NUnit.AgentTester`2..ctor(String username, Object args) in /Users/piotr.karpala/projects/Beef/tools/Beef.Test.NUnit/AgentTester.cs:line 898
   at Beef.Test.NUnit.AgentTester.Create[TAgent,TValue](String username, Object args) in /Users/piotr.karpala/projects/Beef/tools/Beef.Test.NUnit/AgentTester.cs:line 356
   at Beef.Demo.Test.XParallelPersonTest.OneTimeSetUp() in /Users/piotr.karpala/projects/Beef/samples/Demo/Beef.Demo.Test/XParallelPersonTest.cs:line 26


Test Run Failed.
Total tests: 171
     Passed: 8
     Failed: 80
 Total time: 2.9898 Seconds
```
