### ISSUE TITLE
Escaped xml in generated C# code for generic types

### ISSUE THREAD

**Issue by damiankennedy2012** [Avanade/Beef#79]
If an operation parameter type contains escapable xml characters such as in generic types like `List<string>` then the handlebars template will escape these characters giving the non-compilable `List&lt;string&gt;` whenever the parameter type config value is surrounded by two braces `{{ParameterType}}` instead of three `{{{ParameterType}}}`. This only occurs in the minority of cases and is corrected by: https://github.com/Avanade/Beef/pull/78

**Comment by chullybun** [comment]
Pull request accepted; many thanks 👍

However, with the exception of the Web API Controller parameter default. This fix created other issues with the likes of `Create` and `Update` where the value was defaulting to `= default` where the value was not nullable. If a parameter should be defaulted for a controller then the parameter default code-gen configuration should be used; for example: `<Parameter Name="Names" Type="List&lt;string&gt;" Default="default" />`. 

@damiankennedy2012, if you are having an issue with the defaulting are you able to provide further context/example so I can replicate?

Published `Beef.CodeGen.Core` NuGet package version `4.1.6`.

**Comment by damiankennedy2012** [comment]
Cheers for accepting that.

Yeah, nah, I wasn't sure about the default change either. What I did was add to GetTransactions endpoint in Cdr.Banking.xml like this:

  ```
  <Operation Name="GetTransactions" Text="Get transaction for account" OperationType="GetColl" WebApiRoute="{accountId}/transactions" PagingArgs="true" DataCosmosPartitionKey="accountId">
      <!-- Note usage of ValidatorFluent which will inject the code as-is into the validation logic; being a common validator 'Validators.Account' that will perform the authorization check. -->
      <Parameter Name="AccountId" Type="string" ValidatorFluent="Common(Validators.AccountId)" WebApiFrom="FromRoute" IsMandatory="true" />
      <Parameter Name="Args" Type="TransactionArgs" Validator="TransactionArgsValidator" />
      <Parameter Name="SomethingName" Type="List&lt;string&gt;" />
    </Operation>
```
So it might be because I added it as the last parameter that on regen the extra controller method parameter without a default was added after the existing default controller parameters which then caused a syntax error. Will use Default="default" 👍
