### ISSUE TITLE
Incomplete GetHashCode() method generated for an entity that does not define any properties

### ISSUE THREAD

**Issue by Simke11** [Avanade/Beef#80]
When trying to code gen an entity without any properties (only has operations), GetHashCode() is not generated fully and causes compile error. Missing a return and closing }. It comes out as:

```csharp
public override int GetHashCode()
        {
            var hash = new HashCode();
        #region ICopyFrom
```
If a property is added to the entity and re-gen'd, the method is generated correctly, e.g.

```csharp
public override int GetHashCode()
        {
            var hash = new HashCode();
            hash.Add(TestProp);
            return base.GetHashCode() ^ hash.ToHashCode();
        }
```

**Comment by chullybun** [comment]
@Simke11 - first up, welcome back :-) I have a question based on your comment that you are generating an entity without any properties (only has operations), is why are you generating the entity itself - will it serve any purpose? Maybe you could exclude the entity code-gen itself, and only gen the operation-related artefacts. Use `ExcludeEntity="true"` code-gen attribute on the `Entity` -  you will then need to manually remove the existing (redundant) file.

Aside from above thoughts, yes there is an issue with the template that needs correcting. Just trying to understand the urgency? Let me know whether the `ExcludeEntity="true"` will unblock you? Either way we'll keep this issue open until fixed.

Cheers...

**Comment by Simke11** [comment]
Thanks! It was a "legacy" entity that someone else has already defined. It only implements a few custom methods in manager (and no data layer), so my first thought was that it could have just been implemented as a custom manager class outside of code gen. 
I think it was done this way just because it was created by a new developer at a time and they must have thought that everything needs to be defined in codegen xml.
I've worked around compile issue by just adding a single property (which isn't used), but I'll change it to ExcludeEntity="true".
Since we can get around the compile issue, don't think the urgency is high on this one.

**Comment by chullybun** [comment]
Hi @Simke11, issue is fixed. Published NuGet package Beef.CodeGen.Core version 4.1.7. Cheers...

**Comment by edjo23** [comment]
Hi  @chullybun and @Simke11, I also hit this issue in another one of our solutions. Our scenario is that we have multiple entities that inherit a base entity, and in once inheritance scenario there are no additional properties added to the definition.

**Comment by chullybun** [comment]
@edjo23, did the latest NuGet update correct the issue? If not, I need a bit more information to be able to replicate.

**Comment by edjo23** [comment]
Hi @chullybun, sorry for the late reply (I took some time off and went away for a week). I haven't had a chance to check it out yet. Will try and test it out soon.
