### ISSUE TITLE
ExecutionContext.Current.CorrelationId only set for http requests?

### ISSUE THREAD

**Issue by Simke11** [Avanade/Beef#83]
Ran into an issue with integration tests, correlation id and event publishing.
When I have a test that uses an agent tester, execution context correlation id gets set as expected and everything works ok.
If i try to run a test that doesn't use agent tester and directly calls manager or data method, execution context correlation id value is null. If that method also publishes an event, it throws an exception "The ExecutionContext.CorrelationId must be set for the ExpectEventPublisher to function conrrectly."
Is this intended behaviour?
I can get around the exception by explicitly setting correlation id value in test, but this is possibly not the right way to do it. Doco says not to set correlation id directly, as its set by the framework.

**Comment by chullybun** [comment]
@Simke11, no not the intended behaviour, but not one I had validated. I have now updated `ExpectEventPublisher` to swallow (ignore) where the `ExecutionContext.CorrelationId` is `null`; it doesn't need to log where `null` as there would be no means to reconcile - fyi, this is used by the `AgentTester` to assist with the validation of the events raised. I have also updated the documentation to soften the language around the `CorrelationId`, as there is no real reason why it cannot be updated. Cheers...
