### ISSUE TITLE
Escape codes in property annotations not generating correctly

### ISSUE THREAD

**Issue by Nathan-Priebe** [Avanade/Beef#85]
I have hit a issue when generating entities with XML escape codes in a properties annotation value. Any escape codes entered for an annotation don't correctly generate. Previously in beef v3 the escape codes would generate code with the value that the escape code was for. Since upgrading to v4, this no longer seems to work. Is this a configuration issue with the code gen file or new intended behaviour?

As an example if I have this code in the codegen file:
`
<Property Name="MyObject" Type="int" Annotation1="[XmlElement(&quot;MYOBJECT&quot;)]"/>
`

It generates:
`
[XmlElement(&quot;MYOBJECT&quot;)]
`

I expected it to actually generate:
`
[XmlElement("MYOBJECT")]
`

Beef Version: V4.1.4

**Comment by chullybun** [comment]
Hi @Nathan-Priebe, this has been fixed. NuGet package `Beef.CodeGen.Core` version `4.1.8` has been published. Cheers...

**Comment by Nathan-Priebe** [comment]
Thanks @chullybun
