### ISSUE TITLE
Codegen defaults the class authorised attribute to AllowAnonymous when not provided

### ISSUE THREAD

**Issue by Mareeza92** [Avanade/Beef#91]
Previously when the Codegen WebApiAuthorize attribute was not provided, it didn't set the authorised on the controller class. This allowed us to override individual methods to specify different policies at the method level. Now it appears that if no value is provided the "AllowAnonymous" attribute is appended to the class which bypasses any policy authorisation at the method level. This opens up all the methods within the class to unauthorised access.

**Comment by chullybun** [comment]
Hi @Mareeza92. I have reviewed the current templates and existing behaviour. It should now act as follows:

- Controller level - will only output where specified; will no longer default to `AllowAnonymous`.
- Method level - will only output where specified; will no longer default to parent (entity) value.

NuGet package `Beef.CodeGen.Core` version `4.1.11` published.

Cheers...

**Comment by chullybun** [comment]
Closing as there has been no further feedback for a week.
