### ISSUE TITLE
AddGeneratedServices methods causing compilation error when there are no services

### ISSUE THREAD

**Issue by Simke11** [Avanade/Beef#93]
E.g. AddGeneratedDataSvcServices, AddGeneratedManagerServices, AddGeneratedDataServices.

Scenario - 
None of the entities defined in codegen XML have managers, or data or dataSvc layers. In our particular case code gen in the project was only used to define entity properties, without any operations.

Extensions are generated with empty bodies, e.g.
```csharp
public static IServiceCollection AddGeneratedManagerServices(this IServiceCollection services)
{
}
```

Since the methods are expected to return IServiceCollection, this causes compilation error.

In this instance it should probably just return IServiceCollection that was passed in.

**Comment by chullybun** [comment]
@Simke11, I have made a change such that they are not generated at all if there is nothing within. I think this is more correct, in that if you have no operations at all, you may not have a `Business` project for them to be generated into. So you can safely remove the old broken versions from your solution.

NuGet package `Beef.CodeGen.Core` version `4.1.12` has been published.

So where are you at with the rollout of the _Handlebars_ code-gen changes across the solutions? Next is the _Handlebars_ code-gen for all of the database objects. And given you are the DB expert :-) you would be the very best person to validate at your end. When ready, I will create pre-release packages to verify before releasing proper. Let me know.

Cheers...

**Comment by Simke11** [comment]
We now have a new set of "common" libraries (mostly re-written and expanded, old common ones are gone), and we are now getting all Beef libraries via these new packages, even the code gen. No solutions now reference Beef nugets directly.
What that means is that we are still on the old version of Beef v4 (we haven't upgraded to get the bug fixes raised over the last few weeks, but don't let that discourage you :) ).
We are waiting to get all solutions upgraded first before we start using the latest Beef packages and handlebars.
Having said that, more than happy to look at handlebars stuff when its ready to test.
